hw0301:
	gcc hw0301.c myfunc.c -lm -o hw0301

hw0302:
	gcc hw0302.c mystddev.c -lm -o hw0302

hw0303:
	gcc hw0303.c resistance.c -lm -o hw0303

hw0304-1:
	gcc hw0304-1.c hanoi.c -lm -o hw0304-1

hw0304-2:
	gcc hw0304-2.c hanoi.c -lm -o hw0304-2

hw0305:
	gcc hw0305.c smallten.c logic.c -lm -o hw0305

all:
	gcc hw0301.c myfunc.c -lm -o hw0301
	gcc hw0302.c mystddev.c -lm -o hw0302
	gcc hw0303.c resistance.c -lm -o hw0303
	gcc hw0304-1.c hanoi.c -lm -o hw0304-1
	gcc hw0304-2.c hanoi.c -lm -o hw0304-2
	gcc hw0305.c smallten.c logic.c -lm -o hw0305