hw0201:
	[-f hw0201] && rm hw0201
	gcc hw0201.c -lm -o hw0201
	echo "hw0201 has been created!

hw0202:
	echo "I accidentally removed hw0202 when making the makefile :<"

hw0203:
	[-f hw0203] && rm hw0203
	gcc hw0203.c -lm -o hw0203
	echo "hw0203 has been created!

hw0204:
	echo "I accidentally removed hw0204 when making the makefile :<"

hw0205:
	echo "I accidentally removed hw0205 when making the makefile :<"


all:
	gcc hw0201.c -lm -o hw0201
	gcc hw0203.c -lm -o hw0203
	echo "hw0201 and hw0203 has ben created!"
	echo "i accidentally removed the rest :<"

clear:
	[-f hw0201] && rm hw0201
	[-f hw0203] && rm hw0203
