mid01:
	gcc mid01.c -lm -o MID01
	echo "MID01 has been created!"
mid04:
	gcc mid04.c -lm -o MID04
	echo "MID04 has been created!"

mid05.c:
	gcc mid05.c -lm -o MID05
	echo "MID05 has been created!"

all:
	gcc mid01.c -lm -o MID01
	gcc mid04.c -lm -o MID04